#!/bin/bash

echo "=========================================="
echo "TGM Suite - Superadmin Setup Complete"
echo "=========================================="
echo ""
echo "✓ Database migration completed"
echo "✓ Superadmin user created"
echo "✓ Admin dashboard created"
echo ""
echo "Superadmin Credentials:"
echo "  Email: admin@tgmsuite.com"
echo "  Password: admin123"
echo ""
cd "$(dirname "$0")/public"
echo "Total reports in system: $(sqlite3 turfgrass.db 'SELECT COUNT(*) FROM reports;')"
echo "Total users in system: $(sqlite3 turfgrass.db 'SELECT COUNT(*) FROM users;')"
echo "Total fields in system: $(sqlite3 turfgrass.db 'SELECT COUNT(*) FROM fields;')"
cd - > /dev/null
echo ""
echo "To access the admin panel:"
echo "  1. Navigate to your application URL"
echo "  2. Log in with the superadmin credentials above"
echo "  3. Click the 'Admin' link in the navigation bar"
echo "  4. View all 754 submissions across all fields"
echo ""
echo "⚠️  IMPORTANT: Change the admin password after first login!"
echo "=========================================="
